browserstack-sdk robot
BrowserStackCE/browserstack-examples-robot pull request #9
Opened 2023-01-05 15:30 UTC by adarshTS

2023-01-05 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BrowserStackCE/browserstack-examples-robot?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BrowserStackCE/browserstack-examples-robot?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BrowserStackCE/browserstack-examples-robot?pullRequest=9) it.</sub>

2023-01-05 19:20 UTC, princebaretto99 requested changes

2023-01-05 19:20 UTC, princebaretto99 commented on .pabotsuitenames
> +--suite Suites.User.User Tests
Remove this file

2023-01-05 19:20 UTC, princebaretto99 commented on README.md
> +    git checkout sdk-develop
Replace with main

2023-01-05 19:20 UTC, princebaretto99 commented on README.md
> +  browserstack-sdk robot /path/to/test.robot .
Fix this

2023-01-05 19:20 UTC, princebaretto99 commented on README.md
> +  This run profile executes the specific test scenario in browserstack on the browsers configured in your `browserstack.yml` file.
replace with PLatforms

2023-01-05 19:20 UTC, princebaretto99 commented on README.md
> +  browserstack-sdk pabot path/to/testsuiteFolder .
Fix this

2023-01-05 19:20 UTC, princebaretto99 commented on README.md
> +  This run profile executes the entire test suite parallely in browserstack on the browsers configured in your `browserstack.yml` file.
PLatforms

2023-01-05 19:20 UTC, princebaretto99 commented on resources/conf/runners/Library.py
> +    import time
Shift to first line

2023-01-05 19:34 UTC, princebaretto99 submitted a review, later dismissed

2023-01-06 07:42 UTC, samirans89 commented on resources/conf/runners/keywords.robot
> +    # Go To    http://bstackdemo.com/
needed or can be deleted?

2023-01-06 11:33 UTC, adarshTS commented on resources/conf/runners/keywords.robot
> +    # Go To    http://bstackdemo.com/
Can be deleted, removed the comments.

2023-01-06 11:42 UTC, princebaretto99 approved these changes

2023-01-06 11:46 UTC, merged